# Generated by Django 2.2.5 on 2019-09-17 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='packet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=255, verbose_name='Логин')),
                ('password', models.CharField(max_length=255, verbose_name='Пароль')),
                ('firstname', models.CharField(max_length=255, verbose_name='Имя')),
                ('secondname', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('email', models.CharField(max_length=255, verbose_name='e-mail')),
                ('token', models.CharField(max_length=255, verbose_name='token')),
                ('date', models.DateField(verbose_name='Дата')),
            ],
            options={
                'unique_together': {('login', 'password')},
            },
        ),
        migrations.CreateModel(
            name='gps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.FloatField(verbose_name='Долгота')),
                ('latitude', models.FloatField(verbose_name='Широта')),
                ('packet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.packet')),
            ],
        ),
    ]
