# Generated by Django 2.2.5 on 2019-09-25 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='packet',
            name='Way',
            field=models.FloatField(default=0, verbose_name='Путь'),
            preserve_default=False,
        ),
    ]
