# Generated by Django 2.2.5 on 2019-09-25 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_packet_way'),
    ]

    operations = [
        migrations.AddField(
            model_name='gps',
            name='time',
            field=models.FloatField(default=0, verbose_name='Время трекинга'),
            preserve_default=False,
        ),
    ]
