# Generated by Django 2.2.5 on 2019-09-26 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0007_auto_20190926_0009'),
    ]

    operations = [
        migrations.AddField(
            model_name='gps',
            name='alt',
            field=models.FloatField(default=0, verbose_name='Высота'),
            preserve_default=False,
        ),
    ]
